steps:
  # 🔁 Step 1: Restart the GKE Deployment
  - name: gcr.io/cloud-builders/kubectl
    id: Restart Deployment
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-east1-b
      - CLOUDSDK_CONTAINER_CLUSTER=sentiment-cluster
    args:
      - rollout
      - restart
      - deployment
      - sentiment-analyzer

  # ⏳ Step 2: Wait for Rollout to Complete
  - name: gcr.io/cloud-builders/kubectl
    id: Wait for Deployment Rollout
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-east1-b
      - CLOUDSDK_CONTAINER_CLUSTER=sentiment-cluster
    args:
      - rollout
      - status
      - deployment
      - sentiment-analyzer

  # 🚀 Step 3: Trigger Data Drift Detection Job
  - name: gcr.io/cloud-builders/kubectl
    id: Trigger Drift Detection
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-east1-b
      - CLOUDSDK_CONTAINER_CLUSTER=sentiment-cluster
    args:
      - apply
      - '-f'
      - data-drift-job.yaml

options:
  logging: CLOUD_LOGGING_ONLY
